core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipe.urls")),
    path("", include("user_system.urls")),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='user_system/auth/mail/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='user_system/auth/mail/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

recipe/urls.py
from django.urls import path
from recipe.views import (
    CategoryListView,
    CategoryDeleteView,
    CategoryCreateView,
    CategoryUpdateView,
    ProductListView,
    ProductDeleteView,
    ProductUpdateView,
    ProductCreateView,
    RecipeListView,
    UserRecipesListView,
    create_recipe,
    RecipeDetailView,
    RecipeDeleteView,
    RecipeUpdateView,
    DietCreateView,
    DietDeleteView,
    DietUpdateView,
    DietListView,
    DietDetailView,
    MainMenuView,
    RecipeLike,
    UserFavListView
)

urlpatterns = [
    path('', MainMenuView.as_view(), name="main"),


    path("category_list/", CategoryListView.as_view(), name="category_list"),
    path("delete_category/<int:pk>", CategoryDeleteView.as_view(), name="delete_category"),
    path("create_category/", CategoryCreateView.as_view(), name="create_category"),
    path("update_category/<int:pk>", CategoryUpdateView.as_view(), name="update_category"),

    path("product_list/", ProductListView.as_view(), name="product_list"),
    path("create_product/", ProductCreateView.as_view(), name="create_product"),
    path("delete_product/<int:pk>", ProductDeleteView.as_view(), name="delete_product"),
    path("update_product/<int:pk>", ProductUpdateView.as_view(), name="update_product"),

    path("create_diet/", DietCreateView.as_view(), name="create_diet"),
    path("delete_diet/<int:pk>", DietDeleteView.as_view(), name="delete_diet"),
    path("update_diet/<int:pk>", DietUpdateView.as_view(), name="update_diet"),
    path("diet_list/<int:pk>", DietDetailView.as_view(), name="diet_detail"),
    path("diet_list/", DietListView.as_view(), name="diet_list"),

    path("create_recipe/", create_recipe, name="create_recipe"),
    path("recipes/", RecipeListView.as_view(), name='recipe_list'),
    path("delete_recipe/<int:pk>", RecipeDeleteView.as_view(), name='delete_recipe'),
    path("update_recipe/<int:pk>", RecipeUpdateView.as_view(), name='update_recipe'),
    path("user_recipes/<int:pk>", UserRecipesListView.as_view(), name='user_recipes'),
    path("user_recipes/", UserRecipesListView.as_view(), name='user_recipes'),
    path("recipes/<int:pk>", RecipeDetailView.as_view(), name='recipe'),
    path('like/<int:pk>', RecipeLike.as_view(), name='recipe_like'),
    path('recipes/fav/', UserFavListView.as_view(), name='fav_recipes'),
]

app_name = "recipe"

recipe/forms.py
from django import forms
from recipe.models import Category, Product, Recipe, RecipeIngridient, Diet
from django.forms import inlineformset_factory


IngridientInlineFormSet = inlineformset_factory(
    Recipe,
    RecipeIngridient,
    fields=(
        "product",
        "weight",
        "weight_unit",
    ),
    extra=1,
    widgets={
        'product': forms.Select(attrs={'class': 'prod_select form-select'}),
        'weight': forms.NumberInput(
            attrs={
                'class': 'form-control',
                'type': 'number',
                'min': '0',
                'style': 'max-width:200px',
                'placeholder': 'Weight'
            }
        ),
        'weight_unit': forms.Select(
            attrs={
                'class': 'form-select',
                'style': 'width:130%;',
            }
        )
    },
    labels={
        'product': '',
        'weight': '',
        'weight_unit': ''
    }
)


class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngridient
        fields = ["product", "weight", "weight_unit"]


class RecipeCreateForm(forms.ModelForm):
    class Meta:
        model = Recipe

        fields = [
            "title",
            "main_image",
            "url_yt_video",
            "is_dividible",
            "introduction",
            "recipe_text"
        ]

        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "main_image": forms.FileInput(attrs={"class": "form-control"}),
            "url_yt_video": forms.TextInput(
                attrs={"class": "form-control", "type": "url"}
            ),
            "is_dividible": forms.CheckboxInput(attrs={"class": "form-checkbox"}),
            "introduction": forms.TextInput(attrs={"class": "form-control"}),
            "recipe_text": forms.Textarea(attrs={"class": "form-control"}),
        }


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category

        fields = ["name"]

        widgets = {"name": forms.TextInput(attrs={"class": "form-control"})}

        labels = {
            "name": "Category name",
        }


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product

        fields = ["name", "calories", "category", "piece_weight"]

        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "category": forms.Select(attrs={"class": "form-select"}),
            "piece_weight": forms.NumberInput(attrs={
                    "class": "form-select",
                    "placeholder": "Piece weight",
                    'type': 'number',
                    'min': '0'
                }
            )
        }

        labels = {
            "name": "Name",
            "calories": "Calories (per 100 grams)",
            "piece_weight": (
                'Enter piece weight in grams '
                '(If product is countable)'
            )
        }


class DietCreateForm(forms.ModelForm):
    class Meta:
        model = Diet

        fields = ["name", "forriben_categories", "caloires_per_dish"]

        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "forriben_categories": forms.SelectMultiple(
                attrs={
                    "class": "form-control"
                }
            ),
            "caloires_per_dish": forms.NumberInput(
                attrs={
                    "class": "form-select",
                    "min": 0
                }
            )
        }

        labels = {
            "forriben_categories":  (
                "Forriben categories"
                "(cmd button to select)"
            ),
            "caloires_per_dish": (
                "Callories per dish "
                "(If diet needs low callories)"
            )
        }

recipe/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView, TemplateView
from django.template.defaulttags import register
from recipe.models import Category, Product, Recipe, Diet, RecipeIngridient
from django.urls import reverse_lazy
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from recipe.forms import CategoryCreateForm, ProductCreateForm, RecipeCreateForm, IngridientInlineFormSet, DietCreateForm
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from user_system.models import UserPreference
from django.db.models import Q
from user_system.models import CustomUser
from recipe.mixins import UserIsOwnerMixin


class MainMenuView(TemplateView):
    template_name = "recipe/main.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["new_recipes"] = Recipe.objects.all().order_by("-upload_date")[:10]
        return context


@login_required(login_url="log_in/")
def create_recipe(request):
    recipe = Recipe()
    recipe_form = RecipeCreateForm(instance=recipe)
    formset = IngridientInlineFormSet(instance=recipe)
    if request.method == "POST":
        recipe_form = RecipeCreateForm(request.POST, request.FILES)
        formset = IngridientInlineFormSet(request.POST, request.FILES)
        if recipe_form.is_valid():
            created_recipe = recipe_form.save(commit=False)
            formset = IngridientInlineFormSet(
                request.POST, request.FILES, instance=created_recipe
            )

            if formset.is_valid():
                created_recipe.author = request.user
                created_recipe.save()
                formset.save()
                created_recipe.save()
                return HttpResponseRedirect(reverse_lazy('recipe:recipe_list'))
    context = {"recipe_form": recipe_form, "formset": formset, "product_list": Product.objects.all()}
    return render(
        template_name="recipe/recipe/create_form.html", context=context, request=request
    )


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipe/recipe/list_view.html"
    context_object_name = "recipes"
    paginate_by = 20

    def get_queryset(self):
        for_user = self.request.GET.get("user_filter")
        order = self.request.GET.get("order")
        search = self.request.GET.get("search")
        user = self.request.user
        query = Recipe.objects.all()
        if not user.is_anonymous:
            if for_user:
                query = user.preference.recipe_prefernce_filter(for_user)
        
        if search:
            query = query.filter(
                Q(title__icontains=search) |
                Q(ingredients__product__name__icontains=search)
            )
        
        if order and order != "revelant":
            orders = {
                "new": "-upload_date",
                "old": "upload_date"
            }
            query = query.order_by(orders[order])
        
        
        return query.distinct()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order_text = self.request.GET.get('order')
        search_text = self.request.GET.get('search')

        context["order_text"] = order_text if order_text else ''
        context["search_text"] = search_text if search_text else ''

        return context


class RecipeLike(UpdateView, LoginRequiredMixin):
    model = Recipe
    fields='__all__'

    def get_object(self):
        post_id = self.kwargs.get("pk")
        return get_object_or_404(Recipe, pk=post_id)

    def post(self, request, *args, **kwargs):
        recipe = self.get_object()
        user = request.user
        if user in recipe.likes.all():
            recipe.likes.remove(user)
        else:
            recipe.likes.add(user)
        recipe.save()
        return HttpResponseRedirect(request.POST.get('next', '/'))


class UserRecipesListView(ListView, LoginRequiredMixin):
    model = Recipe
    template_name = "recipe/recipe/user_recipes.html"
    context_object_name = "recipes"
    paginate_by = 20

    def get_queryset(self):
        for_user = self.request.GET.get("user_filter")
        order = self.request.GET.get("order")
        search = self.request.GET.get("search")
        user = self.request.user

        try:
            author=self.kwargs['pk']
        except:
            author=self.request.user
        
        query = Recipe.objects.filter(author= author)
        if not user.is_anonymous:
            if for_user:
                query = user.preference.recipe_prefernce_filter(for_user)

        if search:
            query = query.filter(
                Q(title__icontains=search) |
                Q(ingredients__product__name__icontains=search)
            )

        if order and order != "revelant":
            orders = {
                "new": "-upload_date",
                "old": "upload_date"
            }
            query = query.order_by(orders[order])

        return query.distinct()

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        order_text = self.request.GET.get('order')
        search_text = self.request.GET.get('search')

        try:
            user = CustomUser.objects.get(pk=self.kwargs['pk'])
        except:
            user = self.request.user

        context["order_text"] = order_text if order_text else ''
        context["search_text"] = search_text if search_text else ''
        context["user"] = user
        return context


class UserFavListView(ListView, LoginRequiredMixin):
    model = Recipe
    template_name = "recipe/recipe/user_favorites.html"
    context_object_name = "recipes"
    paginate_by = 20

    def get_queryset(self):
        user = CustomUser.objects.get(pk=self.request.user.pk)
        for_user = self.request.GET.get("user_filter")
        query = user.favorite.all()
        search = self.request.GET.get("search")
        order = self.request.GET.get("order")

        if not user.is_anonymous:
            if for_user:
                query = user.preference.recipe_prefernce_filter(for_user)

        if search:
            query = query.filter(
                Q(title__icontains=search) |
                Q(ingredients__product__name__icontains=search)
            )

        if order and order != "revelant":
            orders = {
                "new": "-upload_date",
                "old": "upload_date"
            }
            query = query.order_by(orders[order])

        return query.distinct()

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        order_text = self.request.GET.get('order')
        search_text = self.request.GET.get('search')

        try:
            user = CustomUser.objects.get(pk=self.kwargs['pk'])
        except:
            user = self.request.user

        context["order_text"] = order_text if order_text else ''
        context["search_text"] = search_text if search_text else ''
        context["user"] = user
        return context


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipe/recipe/detail_view.html"
    context_object_name = "recipe"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not self.request.user.is_anonymous:
            try:
                user_pref = UserPreference.objects.get(user=self.request.user)
            except UserPreference.DoesNotExist:
                user_pref = None
        else:
            user_pref = None
        if user_pref:
            fav_cat = user_pref.fav_categories.all()
            fav_prod = user_pref.fav_products.all()
            hate_cat = user_pref.hate_categories.all()
            hate_prod = user_pref.hates_products.all()
        else:
            fav_cat = fav_prod = hate_cat = hate_prod = None

        context["user_fav_cat"] = fav_cat
        context["user_fav_prod"] = fav_prod

        context["user_hate_cat"] = hate_cat
        context["user_hate_prod"] = hate_prod

        return context


class RecipeUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = Recipe
    template_name = "recipe/recipe/update_form.html"
    success_url = reverse_lazy("recipe:recipe_list")
    form_class = RecipeCreateForm

    def get_object(self):
        return get_object_or_404(Recipe, pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super(RecipeUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = IngridientInlineFormSet(
                self.request.POST,
                self.request.FILES,
                instance=self.get_object()
            )
        else:
            context['formset'] = IngridientInlineFormSet(
                instance=self.get_object()
            )

        context['img_rec'] = self.get_object().main_image.url if self.get_object().main_image else None

        return context

    def form_valid(self, form):
        ingredient_form = IngridientInlineFormSet(
                self.request.POST,
                self.request.FILES,
                instance=self.get_object()
            )
        if form.is_valid():
            if ingredient_form.is_valid():
                ingredient_form.instance = self.get_object()
                ingredient_form.save()
                self.object = form.save()
                return super(RecipeUpdateView, self).form_valid(form)
            
            return render(
                template_name="recipe/recipe/update_form.html",
                context=self.get_context_data(),

templates/recipe/diet/create_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="m-3 ms-4">
        <div class="btn-group" role="group" aria-label="Basic outlined example">
            <a type="button" class="btn btn-outline-primary" href="{% url 'recipe:category_list' %}">Categories</a>
            <a type="button" class="btn btn-outline-primary" href="{% url 'recipe:product_list' %}">Products</a>
            <a type="button" class="btn btn-outline-primary" href="{% url 'recipe:diet_list' %}">Diets</a>
            <div class="dropdown rounded-0">
                <button class="btn btn-outline-primary rounded-0 rounded-end dropdown-toggle active" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Create
                </button>
                <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'recipe:create_category' %}">Category</a></li>
                <li><a class="dropdown-item" href="{% url 'recipe:create_product' %}">Product</a></li>
                <li><a class="dropdown-item active" href="{% url 'recipe:create_diet' %}">Diet</a></li>
                </ul>
            </div>
        </div>

        <form method="POST" class="w-25 ms-3 mt-3">
            {% csrf_token %}
                
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">Create</button>
                
        </form>
    </div>
{% endblock %}

templates/recipe/diet/delete_confirm.html
{% extends 'base.html' %}
{% block content %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <div class="position-absolute top-50 start-50 translate-middle">
        <h2>Are you sure to delete this diet</h2>
        <div class="fs-6 fw-lighter">(This action cannot be canceled)</div>
        <br>
        <p>Diet: "{{ diet }}"</p>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Delete" class="btn btn-danger">
            <a href="{%url 'recipe:diet_list'%}" class="btn btn-primary">Back</a>

        </form>
    </div>
{% endblock content %}

templates/recipe/diet/detail_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <nav aria-label="breadcrumb" class="m-3 mb-5">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{%url 'recipe:diet_list' %}">Diets</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{diet.name}}</li>
        </ol>
    </nav>

    <div class="container pt-3">
        
        <h1>{{diet.name}}</h1>
        <p>Here you can watch details about diet, there will be a full list of forriben categories.</p>

        <p>Also there you can see if diet has any restrictions to calories per meal.</p>
        <br>
        <p>
            {%if diet.forriben_categories %}
                <h4>Category restrictions:</h4>
                <ul class="list-group w-25 ms-2">
                {% for category in diet.forriben_categories.all %}
                    <a class="list-group-item" data-bs-toggle="offcanvas" href="#offcanvasExample{{category.id}}" role="button" aria-controls="offcanvasExample" style="text-decoration: none;">
                        {{category.name}}
                    </a>
                    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample{{category.id}}" aria-labelledby="offcanvasExampleLabel">
                        <div class="offcanvas-header">
                          <h5 class="offcanvas-title" id="offcanvasExampleLabel">{{category}} products</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                            <ul class="list-group">
                                {%for product in category.products.all%}
                                    <li class="list-group-item">{{product}}</li>
                                {%endfor%}
                            </ul>
                        </div>
                      </div>
                {%endfor%}
                </ul>
            {%endif%}
            {% if diet.caloires_per_dish %}
                Calories per meal: {{diet.caloires_per_dish}}
            {%endif%}
        </p>

    </div>
        
    
{% endblock %}

templates/recipe/diet/list_view.html
{% extends 'base.html' %}

{% block content %}
    <div class="m-3 ms-2">
        <div class="btn-group ms-2" role="group" aria-label="Basic outlined example">
            <a type="button" class="btn btn-outline-primary" href="{% url 'recipe:category_list' %}">Categories</a>
            <a type="button" class="btn btn-outline-primary" href="{% url 'recipe:product_list' %}">Products</a>
            <a type="button" class="btn btn-outline-primary active" href="{% url 'recipe:diet_list' %}">Diets</a>
            <div class="dropdown rounded-0">
                <button class="btn btn-outline-primary rounded-0 rounded-end dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Create
                </button>
                <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'recipe:create_category' %}">Category</a></li>
                <li><a class="dropdown-item" href="{% url 'recipe:create_product' %}">Product</a></li>
                <li><a class="dropdown-item" href="{% url 'recipe:create_diet' %}">Diet</a></li>

                </ul>
            </div>
        </div>
        <form class="d-flex mt-3 ms-2" role="search" style="max-width: 500px; min-width: 250px;">
            <input class="form-control me-2" type="search" placeholder="Search products" aria-label="Search" name="search" value="{{search_text}}">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <div class="">
            <ul class="container_2">
                {% if diets %}
                    {% for diet in diets %}
                        <a href="{% url 'recipe:diet_detail' diet.pk %}" style="text-decoration: none;">
                            <li class="card item mt-3 border">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        {{diet.name}}
                                        <a href="{% url 'recipe:update_diet' diet.id%}" class="text-warning ms-1" style="text-decoration: none;">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                                            </svg>
                                        </a>
                                        <a href="{% url 'recipe:delete_diet' diet.id%}" class="text-danger" style="text-decoration: none;">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                                        </svg>
                                        </a>
                                    </h5>

                                </div>
                            </li>
                        </a>
                    {% endfor %}
                {%else%}
                    <div class="fw-light text-start w-50 ms-2 mt-3">Diets not found</div>
                {%endif%}

            </ul>
            {% if paginator.page_range|length > 1%}
                <nav aria-label="Page navigation example">
                    <ul class="pagination ms-5 ">
                        {% for page_num in paginator.page_range %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endfor %}
                    </ul>
                </nav> 
            {%endif%}
        </div>
    </div>
{% endblock %}

templates/recipe/diet/update_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="m-3 ms-4">
        <div class="btn-group " role="group" aria-label="Basic outlined example">
            <a type="button" class="btn btn-outline-primary" href="{% url 'recipe:category_list' %}">Categories</a>
            <a type="button" class="btn btn-outline-primary" href="{% url 'recipe:product_list' %}">Products</a>
            <a type="button" class="btn btn-outline-primary active" href="{% url 'recipe:diet_list' %}">Diets</a>
            <div class="dropdown rounded-0">
                <button class="btn btn-outline-primary rounded-0 rounded-end dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Create
                </button>
                <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'recipe:create_category' %}">Category</a></li>
                <li><a class="dropdown-item " href="{% url 'recipe:create_product' %}">Product</a></li>
                <li><a class="dropdown-item" href="{% url 'recipe:create_diet' %}">Diet</a></li>
                </ul>
            </div>
        </div>

        <form method="POST" class="w-25 mt-3 ms-3">
            {% csrf_token %}
                
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">Update</button>
                
        </form>
    </div>
{% endblock %}