core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipe.urls")),
    path("", include("user_system.urls")),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='user_system/auth/mail/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='user_system/auth/mail/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

recipe/urls.py
from django.urls import path
from recipe.views import (
    CategoryListView,
    CategoryDeleteView,
    CategoryCreateView,
    CategoryUpdateView,
    ProductListView,
    ProductDeleteView,
    ProductUpdateView,
    ProductCreateView,
    RecipeListView,
    UserRecipesListView,
    create_recipe,
    RecipeDetailView,
    RecipeDeleteView,
    RecipeUpdateView,
    DietCreateView,
    DietDeleteView,
    DietUpdateView,
    DietListView,
    DietDetailView,
    MainMenuView,
    RecipeLike,
    UserFavListView
)

urlpatterns = [
    path('', MainMenuView.as_view(), name="main"),


    path("category_list/", CategoryListView.as_view(), name="category_list"),
    path("delete_category/<int:pk>", CategoryDeleteView.as_view(), name="delete_category"),
    path("create_category/", CategoryCreateView.as_view(), name="create_category"),
    path("update_category/<int:pk>", CategoryUpdateView.as_view(), name="update_category"),

    path("product_list/", ProductListView.as_view(), name="product_list"),
    path("create_product/", ProductCreateView.as_view(), name="create_product"),
    path("delete_product/<int:pk>", ProductDeleteView.as_view(), name="delete_product"),
    path("update_product/<int:pk>", ProductUpdateView.as_view(), name="update_product"),

    path("create_diet/", DietCreateView.as_view(), name="create_diet"),
    path("delete_diet/<int:pk>", DietDeleteView.as_view(), name="delete_diet"),
    path("update_diet/<int:pk>", DietUpdateView.as_view(), name="update_diet"),
    path("diet_list/<int:pk>", DietDetailView.as_view(), name="diet_detail"),
    path("diet_list/", DietListView.as_view(), name="diet_list"),

    path("create_recipe/", create_recipe, name="create_recipe"),
    path("recipes/", RecipeListView.as_view(), name='recipe_list'),
    path("delete_recipe/<int:pk>", RecipeDeleteView.as_view(), name='delete_recipe'),
    path("update_recipe/<int:pk>", RecipeUpdateView.as_view(), name='update_recipe'),
    path("user_recipes/<int:pk>", UserRecipesListView.as_view(), name='user_recipes'),
    path("user_recipes/", UserRecipesListView.as_view(), name='user_recipes'),
    path("recipes/<int:pk>", RecipeDetailView.as_view(), name='recipe'),
    path('like/<int:pk>', RecipeLike.as_view(), name='recipe_like'),
    path('recipes/fav/', UserFavListView.as_view(), name='fav_recipes'),
]

app_name = "recipe"

user_system/urls.py
from django.urls import path

from user_system.views import (
    UserCreateView,
    CustomLoginView,
    CustomLogoutView,
    UserSettingsView,
    UserUpdateView,
    ResetPasswordView,
    DeleteUserView,
    UserPreferenceUpdateView,
    UserPreferenceCreateView,
    UserFavorite
)


urlpatterns = [
    path("register/", UserCreateView.as_view(), name="register"),
    path("log_in/", CustomLoginView.as_view(), name="log_in"),
    path("log_out/", CustomLogoutView.as_view(), name="log_out"),
    path("settings/", UserSettingsView.as_view(), name='settings'),
    path("edit_user/<int:pk>", UserUpdateView.as_view(), name="update_user"),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path("delete_user/<int:pk>", DeleteUserView.as_view(), name="delete_user"),
    path("preferences/", UserPreferenceCreateView.as_view(), name="create_pref"),
    path("preferences/<int:pk>", UserPreferenceUpdateView.as_view(), name="edit_pref"),
    path("favorite/<int:pk>", UserFavorite.as_view(), name="fav_recipe"),
]

app_name = "user_system"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="icon" type="image/svg+xml" href="{% static 'img/icons/cooking.svg' %}">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <title>Cuisiner</title>
    <style>
        html {
        scroll-behavior: smooth;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm border-bottom p-3 sticky-top bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                Cuisiner
                <img src="{% static 'img/icons/cooking.svg' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse pt-2" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item ">
                      <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'recipe:recipe_list' %}">Recipes</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item pe-2">
                            <a class="nav-link" href="{% url 'recipe:fav_recipes' %}">Favorite</a>
                        </li>
                    {%endif%}

                    </ul>
                    {% if request.user.is_authenticated %}
                        <div class="dropdown d-flex me-5 mb-1">
                            <button class="btn dropdown ps-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {%if request.user.avatar %}
                                    <img src="{{request.user.avatar.url}}" class="rounded-circle" width="30" height="30" style="object-fit: cover;">
                                {%else%}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle mb-1" viewBox="0 0 16 16">
                                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                                    </svg>
                                {%endif%}
                                {{request.user.username}}
                            </button>
                            <ul class="dropdown-menu w-25">
                                <li><a class="dropdown-item text-primary" href="{% url 'recipe:user_recipes'%}">
                                    Profile
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-bounding-box pb-1 " viewBox="0 0 16 16">
                                        <path d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5M.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5m15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5"/>
                                        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                        </svg>
                                </a></li>
                                {% if request.user.is_staff  %}
                                    <li><a class="dropdown-item" href="{% url 'recipe:category_list' %}">
                                        Staff
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-incognito pb-1" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="m4.736 1.968-.892 3.269-.014.058C2.113 5.568 1 6.006 1 6.5 1 7.328 4.134 8 8 8s7-.672 7-1.5c0-.494-1.113-.932-2.83-1.205l-.014-.058-.892-3.27c-.146-.533-.698-.849-1.239-.734C9.411 1.363 8.62 1.5 8 1.5s-1.411-.136-2.025-.267c-.541-.115-1.093.2-1.239.735m.015 3.867a.25.25 0 0 1 .274-.224c.9.092 1.91.143 2.975.143a30 30 0 0 0 2.975-.143.25.25 0 0 1 .05.498c-.918.093-1.944.145-3.025.145s-2.107-.052-3.025-.145a.25.25 0 0 1-.224-.274M3.5 10h2a.5.5 0 0 1 .5.5v1a1.5 1.5 0 0 1-3 0v-1a.5.5 0 0 1 .5-.5m-1.5.5q.001-.264.085-.5H2a.5.5 0 0 1 0-1h3.5a1.5 1.5 0 0 1 1.488 1.312 3.5 3.5 0 0 1 2.024 0A1.5 1.5 0 0 1 10.5 9H14a.5.5 0 0 1 0 1h-.085q.084.236.085.5v1a2.5 2.5 0 0 1-5 0v-.14l-.21-.07a2.5 2.5 0 0 0-1.58 0l-.21.07v.14a2.5 2.5 0 0 1-5 0zm8.5-.5h2a.5.5 0 0 1 .5.5v1a1.5 1.5 0 0 1-3 0v-1a.5.5 0 0 1 .5-.5"/>
                                        </svg>
                                    </a></li>
                                {%endif%}
                                <li><a class="dropdown-item" href="{%url 'user_system:settings' %}">
                                    Settings
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-gear pb-1" viewBox="0 0 16 16">
                                        <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492M5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0"/>
                                        <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115z"/>
                                        </svg>
                                </a></li>
                                <li class="dropdown-item">
                                    <form method="post" action="{% url 'user_system:log_out' %}">
                                        {% csrf_token %}
                                        <button type="submit" class="nav-link ps-0 w-100 text-start pt-0 text-danger">
                                            Logout
                                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-right pb-1" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                                                <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                                                </svg>
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    {%else%}
                        <a class="nav-link mb-1 me-5 text-primary" href="{% url 'user_system:log_in' %}">
                            Sign in
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-box-arrow-in-right mb-1" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z"/>
                                <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                            </svg>
                        </a>

                    {%endif%}
            </div>
        </div>
    </nav>
    {% block breadcrump %}
    {% endblock %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger w-50 p-3 m-3">  <!-- singular -->
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}

    {% for field, errors in form.errors.items %}
        <ul class="messages">
        {% for error in errors %}
            <div class="alert alert-danger w-50 mt-2 ms-1" role="alert">
                {{error}}
            </div>
        {% endfor %}
        </ul>
    {% endfor %}
    {% block content %}
    {% endblock %}

    
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


</body>
</html>